### PR TITLE
Merge pull request #10 from mochachain-project/QT-Refresh

### PR DESCRIPTION
**Pull request by AFarpa**
Logo Vertical - resized 💃 
MochaVertical

### CODE REVIEW

**Comment by Nugetzrul3** [comment]
Big logo xD

**Comment by AFarpa** [comment]
Lol.. As far you can resize it .. all good ! High quality images ..
Either way I can resize it myself and re- upload it  💃

**Comment by Nugetzrul3** [comment]
> Lol.. As far you can resize it .. all good ! High quality images ..
> Either way I can resize it myself and re- upload it

It looks nice

**Comment by AFarpa** [comment]
> 
> 
> > Lol.. As far you can resize it .. all good ! High quality images ..
> > Either way I can resize it myself and re- upload it
> 
> It looks nice

Thanks 👍  ! Guess is not missing a things  right now ! I will hear from Will later one

**Comment by AFarpa** [comment]
Guess now it have the right size :D

**Comment by WillWammer** [comment]
@AFarpa Oh geez! Forgot to merge this! Will be included in next release :smile:

**Pull request merged**
